version: '3.8'

services:
  # Production-like container for testing
  wihy-ui-prod:
    build: 
      context: .
      target: production
    ports:
      - "8080:80"
    environment:
      - REACT_APP_ENVIRONMENT=production
      - REACT_APP_WIHY_API_URL=http://wihymlapi.westus2.cloudapp.azure.com
      - REACT_APP_ENABLE_ANALYTICS=true
      - REACT_APP_ENABLE_CACHING=true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Development container with hot reload
  wihy-ui-dev:
    build:
      context: .
      target: builder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_ENVIRONMENT=development
      - REACT_APP_WIHY_API_URL=http://wihymlapi.westus2.cloudapp.azure.com
      - REACT_APP_DEBUG_MODE=true
    volumes:
      - ./client/src:/app/client/src:ro
      - ./client/public:/app/client/public:ro
      - ./client/package.json:/app/client/package.json:ro
    command: sh -c "cd client && npm start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # WiHy ML API (for local development - optional)
  # Uncomment and configure if you have the WiHy ML API container
  # wihy-api:
  #   image: wihy-ml-api:latest
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - ENVIRONMENT=development
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3