version: '3.8'

services:
  wihy-ui:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./staticwebapp.config.json:/app/staticwebapp.config.json:ro

  wihy-ui-dev:
    build:
      context: .
      target: builder
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./client/src:/app/client/src
      - ./client/public:/app/client/public
    command: sh -c "cd client && npm start"