version: '3.8'

services:
  # Production-like container for testing
  wihy-ui-prod:
    build: 
      context: .
      target: production
    ports:
      - "8080:80"
    environment:
      - REACT_APP_ENVIRONMENT=production
      - REACT_APP_API_BASE_URL=https://your-serverless-api.azurewebsites.net/api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development container with hot reload
  wihy-ui-dev:
    build:
      context: .
      target: builder
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_ENVIRONMENT=development
      - REACT_APP_API_BASE_URL=http://localhost:7071/api
    volumes:
      - ./client/src:/app/client/src:ro
      - ./client/public:/app/client/public:ro
    command: sh -c "cd client && npm start"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Local serverless API simulation (Azure Functions Core Tools)
  serverless-api:
    image: mcr.microsoft.com/azure-functions/node:4-node18
    ports:
      - "7071:80"
    environment:
      - AzureWebJobsScriptRoot=/home/site/wwwroot
      - AzureFunctionsJobHost__Logging__Console__IsEnabled=true
    volumes:
      - ./api:/home/site/wwwroot:ro
    command: /azure-functions-host/Microsoft.Azure.WebJobs.Script.WebHost
    depends_on:
      - wihy-ui-dev