import React, { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Users, Activity, Eye, TrendingUp, Copy, Check, Crown, DollarSign } from "lucide-react";
import TrackingHeader from "../components/layout/TrackingHeader";

interface ManagerStats {
  managerId: string;
  managerName: string;
  totalReferrals: number;
  activePartners: number;
  totalClicks: number;
  totalConversions: number;
  conversionRate: number;
  potentialRevenue: number; // Manager's 10% of partners' conversion-based commission
  partners: Array<{
    trackingId: string;
    name: string;
    clicks: number;
    conversions: number;
    lastActive: string;
    status: 'active' | 'inactive';
    revenue: number; // Revenue generated by this partner
  }>;
  recentActivity: Array<{
    partnerName: string;
    trackingId: string;
    campaign: string;
    clicks: number;
    timestamp: string;
  }>;
  clicksByDay: Array<{
    date: string;
    clicks: number;
  }>;
}

function cn(...classes: Array<string | false | null | undefined>) {
  return classes.filter(Boolean).join(" ");
}

function formatDate(ts: string) {
  try {
    return new Date(ts).toLocaleString();
  } catch {
    return ts;
  }
}

function IconTile({
  tone = "blue",
  children,
}: {
  tone?: "blue" | "purple" | "yellow" | "green" | "indigo" | "emerald";
  children: React.ReactNode;
}) {
  const toneMap: Record<string, string> = {
    blue: "bg-blue-50 text-blue-600 ring-blue-100",
    purple: "bg-purple-50 text-purple-600 ring-purple-100",
    yellow: "bg-yellow-50 text-yellow-700 ring-yellow-100",
    green: "bg-green-50 text-green-600 ring-green-100",
    indigo: "bg-indigo-50 text-indigo-600 ring-indigo-100",
    emerald: "bg-emerald-50 text-emerald-600 ring-emerald-100",
  };

  return (
    <div
      className={cn(
        "flex h-14 w-14 items-center justify-center rounded-2xl ring-1 p-3",
        toneMap[tone]
      )}
    >
      {children}
    </div>
  );
}

function StatCard({
  title,
  value,
  deltaText,
  deltaUp = true,
  tone,
  icon,
}: {
  title: string;
  value: string | number;
  deltaText: string;
  deltaUp?: boolean;
  tone: "blue" | "purple" | "yellow" | "green" | "indigo" | "emerald";
  icon: React.ReactNode;
}) {
  return (
    <div className="rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
      <div className="flex items-start justify-between gap-4">
        <div className="overflow-hidden">
          <div className="text-sm font-medium text-slate-500">{title}</div>
          <div className="mt-2 text-4xl font-semibold tracking-tight text-slate-900 overflow-hidden">
            {value}
          </div>

          <div
            className={cn(
              "mt-3 inline-flex items-center gap-2 text-sm font-medium",
              deltaUp ? "text-emerald-600" : "text-rose-600"
            )}
          >
            <span className="text-lg leading-none">{deltaUp ? "↗" : "↘"}</span>
            <span>{deltaText}</span>
          </div>
        </div>

        <IconTile tone={tone}>{icon}</IconTile>
      </div>
    </div>
  );
}

const ManagerDashboard: React.FC = () => {
  const navigate = useNavigate();
  const [stats, setStats] = useState<ManagerStats | null>(null);
  const [loading, setLoading] = useState(true);
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [hasAccess, setHasAccess] = useState(false);

  useEffect(() => {
    fetchManagerStats();
  }, []);

  const fetchManagerStats = async () => {
    try {
      const response = await fetch("/api/manager/stats");
      if (!response.ok) {
        throw new Error("API not available");
      }
      const data = await response.json();
      setStats(data);
      
      // Check if manager has access based on performance
      checkManagerAccess(data);
    } catch (e) {
      console.error("Failed to fetch manager stats, using demo data:", e);
      // Demo data for manager
      const demoStats: ManagerStats = {
        managerId: "mgr_demo_123",
        managerName: "Sarah Johnson",
        totalReferrals: 12,
        activePartners: 8,
        totalClicks: 3421,
        totalConversions: 287,
        conversionRate: 8.4,
        potentialRevenue: 0, // Will be calculated below
        partners: [
          {
            trackingId: "partner_001",
            name: "Wellness Influencer Alex",
            clicks: 892,
            conversions: 78,
            revenue: 7800, // $100 per conversion
            lastActive: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
            status: 'active' as const,
          },
          {
            trackingId: "partner_002",
            name: "Fitness Coach Mike",
            clicks: 673,
            conversions: 61,
            revenue: 6100,
            lastActive: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
            status: 'active' as const,
          },
          {
            trackingId: "partner_003",
            name: "Health Blog Emma",
            clicks: 521,
            conversions: 45,
            revenue: 4500,
            lastActive: new Date(Date.now() - 1000 * 60 * 240).toISOString(),
            status: 'active' as const,
          },
          {
            trackingId: "partner_004",
            name: "Nutrition Expert Lisa",
            clicks: 387,
            conversions: 32,
            revenue: 3200,
            lastActive: new Date(Date.now() - 1000 * 60 * 480).toISOString(),
            status: 'active' as const,
          },
          {
            trackingId: "partner_005",
            name: "Yoga Instructor Tom",
            clicks: 289,
            conversions: 24,
            revenue: 2400,
            lastActive: new Date(Date.now() - 1000 * 60 * 720).toISOString(),
            status: 'active' as const,
          },
          {
            trackingId: "partner_006",
            name: "Wellness Podcast Jane",
            clicks: 234,
            conversions: 19,
            revenue: 1900,
            lastActive: new Date(Date.now() - 1000 * 60 * 1440).toISOString(),
            status: 'active' as const,
          },
          {
            trackingId: "partner_007",
            name: "Health Forum Chris",
            clicks: 198,
            conversions: 15,
            revenue: 1500,
            lastActive: new Date(Date.now() - 1000 * 60 * 2880).toISOString(),
            status: 'active' as const,
          },
          {
            trackingId: "partner_008",
            name: "Fitness Blog David",
            clicks: 156,
            conversions: 11,
            revenue: 1100,
            lastActive: new Date(Date.now() - 1000 * 60 * 4320).toISOString(),
            status: 'active' as const,
          },
          {
            trackingId: "partner_009",
            name: "Nutrition Newsletter Pat",
            clicks: 71,
            conversions: 2,
            revenue: 200,
            lastActive: new Date(Date.now() - 1000 * 60 * 10080).toISOString(),
            status: 'inactive' as const,
          },
        ],
        recentActivity: [
          {
            partnerName: "Wellness Influencer Alex",
            trackingId: "partner_001",
            campaign: "instagram_story",
            clicks: 45,
            timestamp: new Date(Date.now() - 1000 * 60 * 15).toISOString(),
          },
          {
            partnerName: "Fitness Coach Mike",
            trackingId: "partner_002",
            campaign: "youtube_video",
            clicks: 32,
            timestamp: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
          },
          {
            partnerName: "Health Blog Emma",
            trackingId: "partner_003",
            campaign: "blog_post",
            clicks: 28,
            timestamp: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
          },
        ],
        clicksByDay: [],
      };

      // Calculate potential revenue: 10% of partner revenue, capped at 10% of total
      const totalPartnerRevenue = demoStats.partners.reduce((sum, p) => sum + p.revenue, 0);
      const managerCommission = totalPartnerRevenue * 0.10; // 10% of partner revenue
      const cappedCommission = Math.min(managerCommission, totalPartnerRevenue * 0.10);
      demoStats.potentialRevenue = cappedCommission;

      setStats(demoStats);
      checkManagerAccess(demoStats);
    } finally {
      setLoading(false);
    }
  };

  const checkManagerAccess = (data: ManagerStats) => {
    // Primary requirement: Must have at least 20 partners to be a manager
    const hasMinimumPartners = data.totalReferrals >= 20;
    
    if (!hasMinimumPartners) {
      setHasAccess(false);
      console.log('Manager Dashboard Access Denied: Need 20 partners, current:', data.totalReferrals);
      return;
    }
    
    // After meeting minimum, check performance criteria:
    // 1. High activity rate: At least 60% of partners are active
    const activityRate = (data.activePartners / data.totalReferrals) * 100;
    const hasHighActivity = activityRate >= 60;

    // 2. High-performing partners: At least one partner with 500+ clicks OR 50+ conversions
    const hasHighPerformer = data.partners.some(
      (partner) => partner.clicks >= 500 || partner.conversions >= 50
    );

    // 3. Strong network performance: Total network has 1000+ clicks OR 100+ conversions
    const hasStrongNetwork = data.totalClicks >= 1000 || data.totalConversions >= 100;

    // Grant access if any performance criteria is met (after meeting minimum partner count)
    const access = hasHighActivity || hasHighPerformer || hasStrongNetwork;
    setHasAccess(access);

    // Log access decision for debugging
    console.log('Manager Dashboard Access Check:', {
      totalPartners: data.totalReferrals,
      hasMinimumPartners,
      activityRate: activityRate.toFixed(1) + '%',
      hasHighActivity,
      hasHighPerformer,
      hasStrongNetwork,
      accessGranted: access
    });
  };

  const copyPartnerLink = (trackingId: string) => {
    const baseUrl = window.location.origin;
    const link = `${baseUrl}/partner-hub?id=${trackingId}`;
    navigator.clipboard.writeText(link).then(() => {
      setCopiedId(trackingId);
      setTimeout(() => setCopiedId(null), 2000);
    });
  };

  const chartData = useMemo(() => {
    return [
      { height: 62, label: "Mon" },
      { height: 75, label: "Tue" },
      { height: 68, label: "Wed" },
      { height: 85, label: "Thu" },
      { height: 92, label: "Fri" },
      { height: 58, label: "Sat" },
      { height: 45, label: "Sun" },
    ];
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen overflow-hidden" style={{ backgroundColor: '#f0f7ff' }}>
        <TrackingHeader />
        <div className="mx-auto max-w-6xl px-6 py-10">
          <div className="rounded-3xl bg-white p-10 text-center shadow-sm ring-1 ring-slate-200">
            <div className="mx-auto h-5 w-5 animate-spin rounded-full border-2 border-slate-200 border-t-slate-900" />
            <div className="mt-3 text-sm text-slate-600">Loading dashboard...</div>
          </div>
        </div>
      </div>
    );
  }

  if (!stats) {
    return (
      <div className="min-h-screen overflow-hidden" style={{ backgroundColor: '#f0f7ff' }}>
        <TrackingHeader />
        <div className="mx-auto max-w-6xl px-6 py-10">
          <div className="rounded-3xl bg-white p-10 text-center shadow-sm ring-1 ring-slate-200">
            <div className="text-lg font-semibold text-slate-900">No data available</div>
          </div>
        </div>
      </div>
    );
  }

  // Access denied screen - show when manager hasn't met success criteria
  if (!hasAccess) {
    const activityRate = ((stats.activePartners / stats.totalReferrals) * 100).toFixed(1);
    const topPartner = stats.partners.reduce((prev, current) => 
      (prev.clicks > current.clicks) ? prev : current
    );

    return (
      <div className="min-h-screen overflow-hidden" style={{ backgroundColor: '#f0f7ff' }}>
        <TrackingHeader />
        
        <div className="mx-auto max-w-4xl px-6 py-16">
          <div className="rounded-3xl bg-white p-10 shadow-lg ring-1 ring-slate-200">
            <div className="text-center">
              <div className="mx-auto flex h-16 w-16 items-center justify-center rounded-2xl bg-yellow-50 ring-1 ring-yellow-200">
                <Crown className="h-8 w-8 text-yellow-600" />
              </div>
              
              <h1 className="mt-6 text-2xl font-bold text-slate-900">
                {stats.totalReferrals < 20 ? 'Become a Manager' : 'Dashboard Coming Soon!'}
              </h1>
              <p className="mt-2 text-slate-600">
                Hi <span className="font-semibold text-slate-900">{stats.managerName}</span>, 
                {stats.totalReferrals < 20 
                  ? ` recruit ${20 - stats.totalReferrals} more partner${20 - stats.totalReferrals === 1 ? '' : 's'} to unlock manager status and access advanced features.`
                  : ' your manager dashboard will unlock when you achieve success milestones.'
                }
              </p>
            </div>

            <div className="mt-8 rounded-2xl bg-slate-50 p-6 ring-1 ring-slate-200">
              <h3 className="text-sm font-semibold text-slate-900">
                {stats.totalReferrals < 20 ? 'Manager Status Requirements' : 'Unlock Criteria - Achieve Any One:'}
              </h3>
              {stats.totalReferrals < 20 && (
                <p className="mt-1 text-xs text-slate-600">First, recruit 20 partners to qualify for manager status:</p>
              )}
              
              <div className="mt-4 space-y-4">
                <div className="flex items-start gap-3">
                  <div className={cn(
                    "flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-semibold",
                    stats.totalReferrals >= 20
                      ? "bg-green-100 text-green-700"
                      : "bg-slate-200 text-slate-600"
                  )}>
                    {stats.totalReferrals >= 20 ? '✓' : '1'}
                  </div>
                  <div className="flex-1">
                    <div className="text-sm font-medium text-slate-900">Recruit 20 Partners (Required)</div>
                    <div className="text-sm text-slate-600">
                      Build your network to qualify for manager status
                    </div>
                    <div className="mt-1 text-xs font-semibold text-slate-700">
                      Current: {stats.totalReferrals}/20 partners ({stats.totalReferrals >= 20 ? 'Complete! ✓' : `${20 - stats.totalReferrals} needed`})
                    </div>
                  </div>
                </div>

                {stats.totalReferrals >= 20 && (
                  <p className="text-xs text-slate-600 pl-9">
                    ✓ Manager status unlocked! Now achieve ANY ONE performance milestone below:
                  </p>
                )}

                <div className="flex items-start gap-3">
                  <div className={cn(
                    "flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-semibold",
                    (stats.activePartners / stats.totalReferrals) * 100 >= 60
                      ? "bg-green-100 text-green-700"
                      : "bg-slate-200 text-slate-600"
                  )}>
                    {(stats.activePartners / stats.totalReferrals) * 100 >= 60 ? '✓' : '2'}
                  </div>
                  <div className="flex-1">
                    <div className="text-sm font-medium text-slate-900">High Activity Rate</div>
                    <div className="text-sm text-slate-600">
                      60% or more partners actively engaged
                    </div>
                    <div className="mt-1 text-xs font-semibold text-slate-700">
                      Current: {activityRate}% ({stats.activePartners}/{stats.totalReferrals} partners active)
                    </div>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <div className={cn(
                    "flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-semibold",
                    stats.partners.some(p => p.clicks >= 500 || p.conversions >= 50)
                      ? "bg-green-100 text-green-700"
                      : "bg-slate-200 text-slate-600"
                  )}>
                    {stats.partners.some(p => p.clicks >= 500 || p.conversions >= 50) ? '✓' : '3'}
                  </div>
                  <div className="flex-1">
                    <div className="text-sm font-medium text-slate-900">High-Performing Partner</div>
                    <div className="text-sm text-slate-600">
                      At least one partner with 500+ clicks OR 50+ conversions
                    </div>
                    <div className="mt-1 text-xs font-semibold text-slate-700">
                      Top Partner: {topPartner.name} ({topPartner.clicks} clicks, {topPartner.conversions} conversions)
                    </div>
                  </div>
                </div>

                <div className="flex items-start gap-3">
                  <div className={cn(
                    "flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-semibold",
                    stats.totalClicks >= 1000 || stats.totalConversions >= 100
                      ? "bg-green-100 text-green-700"
                      : "bg-slate-200 text-slate-600"
                  )}>
                    {stats.totalClicks >= 1000 || stats.totalConversions >= 100 ? '✓' : '4'}
                  </div>
                  <div className="flex-1">
                    <div className="text-sm font-medium text-slate-900">Strong Network Performance</div>
                    <div className="text-sm text-slate-600">
                      Network generates 1,000+ total clicks OR 100+ conversions
                    </div>
                    <div className="mt-1 text-xs font-semibold text-slate-700">
                      Current: {stats.totalClicks.toLocaleString()} clicks, {stats.totalConversions} conversions
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="mt-6 rounded-2xl bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50 p-6 ring-1 ring-slate-200">
              <h3 className="text-sm font-semibold text-slate-900">Current Progress</h3>
              <div className="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3">
                <div className="rounded-xl bg-white/80 p-4 shadow-sm ring-1 ring-slate-200">
                  <div className="text-xs font-medium text-slate-500">Total Partners</div>
                  <div className="mt-1 text-2xl font-bold text-slate-900">{stats.totalReferrals}</div>
                </div>
                <div className="rounded-xl bg-white/80 p-4 shadow-sm ring-1 ring-slate-200">
                  <div className="text-xs font-medium text-slate-500">Active Partners</div>
                  <div className="mt-1 text-2xl font-bold text-green-600">{stats.activePartners}</div>
                </div>
                <div className="rounded-xl bg-white/80 p-4 shadow-sm ring-1 ring-slate-200">
                  <div className="text-xs font-medium text-slate-500">Total Clicks</div>
                  <div className="mt-1 text-2xl font-bold text-blue-600">{stats.totalClicks.toLocaleString()}</div>
                </div>
                <div className="rounded-xl bg-white/80 p-4 shadow-sm ring-1 ring-slate-200">
                  <div className="text-xs font-medium text-slate-500">Conversions</div>
                  <div className="mt-1 text-2xl font-bold text-purple-600">{stats.totalConversions}</div>
                </div>
                <div className="rounded-xl bg-white/80 p-4 shadow-sm ring-1 ring-slate-200 sm:col-span-2">
                  <div className="text-xs font-medium text-slate-500">Potential Revenue</div>
                  <div className="mt-1 text-2xl font-bold text-emerald-600">${stats.potentialRevenue.toLocaleString()}</div>
                  <div className="mt-1 text-xs text-slate-600">10% of partner earnings</div>
                </div>
              </div>
            </div>

            <div className="mt-8 text-center">
              <p className="text-sm text-slate-600">
                Keep recruiting quality partners and driving engagement. Your dashboard will automatically unlock when you hit any milestone!
              </p>
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen overflow-hidden" style={{ backgroundColor: '#f0f7ff' }}>
      <TrackingHeader />
      
      <div className="mx-auto max-w-6xl px-6 py-10">
        {/* Header */}
        <div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <div className="flex items-center gap-3">
              <h1 className="text-2xl font-semibold tracking-tight text-slate-900">
                Manager Dashboard
              </h1>
              <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-indigo-100 ring-1 ring-indigo-200">
                <Crown className="h-4 w-4 text-indigo-600" />
              </div>
            </div>
            <p className="mt-1 text-sm text-slate-600">
              Welcome back, <span className="font-semibold text-slate-900">{stats.managerName}</span>
            </p>
          </div>

          <div className="flex gap-3">
            <button
              onClick={() => navigate('/payout-settings', { state: { from: '/manager-dashboard' } })}
              className="inline-flex items-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 text-sm font-semibold text-white shadow-sm hover:bg-emerald-700"
            >
              <DollarSign className="h-4 w-4" />
              <span>Get Paid</span>
            </button>
            <div className="rounded-2xl bg-white px-4 py-2 shadow-sm ring-1 ring-slate-200">
              <div className="text-xs font-medium text-slate-500">Manager ID</div>
              <div className="font-mono text-sm font-semibold text-slate-900">{stats.managerId}</div>
            </div>
          </div>
        </div>

        {/* Stats Grid */}
        <div className="mt-6 grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-5">
          <StatCard
            title="Total Referrals"
            value={stats.totalReferrals.toLocaleString()}
            deltaText="Partners recruited"
            deltaUp
            tone="indigo"
            icon={<Users className="h-4 w-4" />}
          />
          <StatCard
            title="Active Partners"
            value={stats.activePartners.toLocaleString()}
            deltaText="Currently engaged"
            deltaUp
            tone="green"
            icon={<Activity className="h-4 w-4" />}
          />
          <StatCard
            title="Total Clicks"
            value={stats.totalClicks.toLocaleString()}
            deltaText="From your network"
            deltaUp
            tone="blue"
            icon={<Eye className="h-4 w-4" />}
          />
          <StatCard
            title="Conversions"
            value={stats.totalConversions.toLocaleString()}
            deltaText={`${stats.conversionRate}% conversion rate`}
            deltaUp
            tone="purple"
            icon={<TrendingUp className="h-4 w-4" />}
          />
          <StatCard
            title="Potential Revenue"
            value={`$${stats.potentialRevenue.toLocaleString()}`}
            deltaText="From partner conversions"
            deltaUp
            tone="emerald"
            icon={<Crown className="h-4 w-4" />}
          />
        </div>

        {/* Performance Chart */}
        <div className="mt-8 rounded-3xl bg-white p-8 shadow-sm ring-1 ring-slate-200">
          <h2 className="text-xl font-semibold text-slate-900">Weekly Performance</h2>
          <p className="mt-1 text-sm text-slate-600">Clicks from your partner network over the last 7 days</p>

          <div className="mt-8 rounded-3xl bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50 p-8 ring-1 ring-slate-200">
            <div className="flex items-end justify-between gap-2" style={{ height: '200px' }}>
              {chartData.map((data, i) => (
                <div
                  key={i}
                  className="group relative flex flex-1 flex-col items-center justify-end"
                  style={{ minWidth: '20px' }}
                >
                  <div
                    className="w-full rounded-t-xl bg-gradient-to-t from-indigo-500 to-purple-500 shadow-lg transition-all duration-300 hover:from-indigo-600 hover:to-purple-600 hover:shadow-xl cursor-pointer"
                    style={{ height: `${data.height}%` }}
                  >
                    <div className="absolute -top-12 left-1/2 -translate-x-1/2 hidden group-hover:block z-10">
                      <div className="rounded-xl bg-slate-900 px-3 py-2 text-xs font-semibold text-white shadow-xl whitespace-nowrap">
                        {Math.round(data.height * 5)} clicks
                      </div>
                    </div>
                  </div>
                </div>
              ))}
            </div>

            <div className="mt-4 flex items-center justify-between gap-2">
              {chartData.map((data, i) => (
                <div key={i} className="flex-1 text-center text-xs font-medium text-slate-600">
                  {data.label}
                </div>
              ))}
            </div>
          </div>
        </div>

        {/* Partners Table */}
        <div className="mt-8 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-semibold text-slate-900">Your Partners</h2>
            <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700 ring-1 ring-slate-200">
              {stats.partners.length} total
            </span>
          </div>

          <div className="mt-4 overflow-hidden rounded-2xl ring-1 ring-slate-200">
            <table className="min-w-full bg-white text-left text-sm">
              <thead className="bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500">
                <tr>
                  <th className="px-4 py-3">Partner Name</th>
                  <th className="px-4 py-3 text-right">Clicks</th>
                  <th className="px-4 py-3 text-right">Conversions</th>
                  <th className="px-4 py-3 text-right">Revenue</th>
                  <th className="px-4 py-3 text-right">Your Earnings</th>
                  <th className="px-4 py-3">Status</th>
                  <th className="px-4 py-3">Last Active</th>
                  <th className="px-4 py-3 text-right">Actions</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100">
                {stats.partners.map((partner) => (
                  <tr key={partner.trackingId} className="hover:bg-slate-50/60">
                    <td className="px-4 py-3">
                      <div className="font-medium text-slate-900">{partner.name}</div>
                      <div className="text-xs text-slate-500 font-mono">{partner.trackingId}</div>
                    </td>
                    <td className="px-4 py-3 text-right font-semibold text-slate-900">
                      {partner.clicks.toLocaleString()}
                    </td>
                    <td className="px-4 py-3 text-right font-semibold text-emerald-600">
                      {partner.conversions}
                    </td>
                    <td className="px-4 py-3 text-right font-semibold text-blue-600">
                      ${partner.revenue.toLocaleString()}
                    </td>
                    <td className="px-4 py-3 text-right font-semibold text-purple-600">
                      ${(partner.revenue * 0.10).toLocaleString()}
                    </td>
                    <td className="px-4 py-3">
                      <span
                        className={cn(
                          "inline-flex rounded-full px-2 py-1 text-xs font-medium ring-1",
                          partner.status === 'active'
                            ? "bg-green-50 text-green-700 ring-green-200"
                            : "bg-slate-50 text-slate-600 ring-slate-200"
                        )}
                      >
                        {partner.status}
                      </span>
                    </td>
                    <td className="px-4 py-3 text-xs text-slate-600">
                      {formatDate(partner.lastActive)}
                    </td>
                    <td className="px-4 py-3 text-right">
                      <button
                        onClick={() => copyPartnerLink(partner.trackingId)}
                        className="inline-flex items-center gap-1.5 rounded-xl bg-white px-3 py-1.5 text-xs font-semibold text-slate-900 shadow-sm ring-1 ring-slate-200 hover:bg-slate-50"
                      >
                        {copiedId === partner.trackingId ? (
                          <>
                            <Check className="h-3 w-3 text-green-600" />
                            <span>Copied!</span>
                          </>
                        ) : (
                          <>
                            <Copy className="h-3 w-3" />
                            <span>Share</span>
                          </>
                        )}
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Recent Activity */}
        <div className="mt-8 rounded-3xl bg-white p-6 shadow-sm ring-1 ring-slate-200">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-semibold text-slate-900">Recent Activity</h2>
            <span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700 ring-1 ring-slate-200">
              Latest
            </span>
          </div>

          <div className="mt-4 space-y-3">
            {stats.recentActivity.map((activity, idx) => (
              <div
                key={idx}
                className="rounded-2xl bg-slate-50 p-4 ring-1 ring-slate-200"
              >
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-100 ring-1 ring-indigo-200">
                      <Activity className="h-5 w-5 text-indigo-600" />
                    </div>
                    <div>
                      <div className="font-medium text-slate-900">{activity.partnerName}</div>
                      <div className="text-sm text-slate-600">
                        <span className="font-mono text-xs">{activity.campaign}</span> • {activity.clicks} clicks
                      </div>
                    </div>
                  </div>
                  <div className="text-xs text-slate-500">
                    {formatDate(activity.timestamp)}
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* Commission Info */}
        <div className="mt-8 rounded-3xl bg-gradient-to-br from-indigo-50 via-purple-50 to-pink-50 p-8 ring-1 ring-slate-200">
          <div className="flex items-start gap-4">
            <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-indigo-600 ring-1 ring-indigo-700">
              <Crown className="h-6 w-6 text-white" />
            </div>
            <div className="flex-1">
              <h3 className="text-xl font-semibold text-slate-900">Manager Performance Summary</h3>
              <p className="mt-2 text-sm text-slate-600">
                You've recruited {stats.totalReferrals} partners who have generated {stats.totalClicks.toLocaleString()} clicks 
                and {stats.totalConversions} conversions. Keep up the great work!
              </p>
              
              <div className="mt-6 rounded-2xl bg-white/80 p-6 shadow-sm ring-1 ring-slate-200">
                <h4 className="text-sm font-semibold text-slate-900 mb-3">Revenue Model</h4>
                <div className="space-y-2 text-sm text-slate-600">
                  <div className="flex items-center gap-2">
                    <div className="h-1.5 w-1.5 rounded-full bg-emerald-500"></div>
                    <span>Earnings based ONLY on conversions (not clicks)</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="h-1.5 w-1.5 rounded-full bg-purple-500"></div>
                    <span>Partners earn 10% commission per conversion</span>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="h-1.5 w-1.5 rounded-full bg-blue-500"></div>
                    <span>Managers earn 10% of their partners' commission</span>
                  </div>
                </div>
                <div className="mt-4 pt-4 border-t border-slate-200">
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-medium text-slate-700">Your Total Potential Revenue:</span>
                    <span className="text-2xl font-bold text-emerald-600">${stats.potentialRevenue.toLocaleString()}</span>
                  </div>
                </div>
              </div>

              <div className="mt-4 grid grid-cols-3 gap-4">
                <div className="rounded-2xl bg-white/80 p-4 shadow-sm ring-1 ring-slate-200">
                  <div className="text-xs font-medium text-slate-500">Avg Clicks/Partner</div>
                  <div className="mt-1 text-2xl font-bold text-slate-900">
                    {Math.round(stats.totalClicks / stats.totalReferrals).toLocaleString()}
                  </div>
                </div>
                <div className="rounded-2xl bg-white/80 p-4 shadow-sm ring-1 ring-slate-200">
                  <div className="text-xs font-medium text-slate-500">Network Conversion Rate</div>
                  <div className="mt-1 text-2xl font-bold text-emerald-600">
                    {stats.conversionRate}%
                  </div>
                </div>
                <div className="rounded-2xl bg-white/80 p-4 shadow-sm ring-1 ring-slate-200">
                  <div className="text-xs font-medium text-slate-500">Active Rate</div>
                  <div className="mt-1 text-2xl font-bold text-indigo-600">
                    {Math.round((stats.activePartners / stats.totalReferrals) * 100)}%
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default ManagerDashboard;
