version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    env_file:
      - .env.example
    depends_on:
      - model

  model:
    image: python:3.8
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    working_dir: /app/src/models
    command: python model_loader.py

networks:
  default:
    driver: bridge

volumes:
  data: