name: Deploy to Azure Container Apps

on:
  # Temporarily disabled until Azure secrets are configured
  # push:
  #   branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY_LOGIN_SERVER: wihy.azurecr.io
  REGISTRY_USERNAME: wihy
  CONTAINER_APP_NAME: wihy-ui
  CONTAINER_APP_ENVIRONMENT: wihy-env
  RESOURCE_GROUP: rg-wihy
  IMAGE_NAME: wihy-ui

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
        username: ${{ env.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64

    # Azure Login using OIDC (Recommended)
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    # Alternative: Use service principal credentials (Legacy)
    # - name: Log in to Azure
    #   uses: azure/login@v2  
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Apps
      uses: azure/container-apps-deploy-action@v1
      with:
        resource-group: ${{ env.RESOURCE_GROUP }}
        container-app-name: ${{ env.CONTAINER_APP_NAME }}
        container-app-environment: ${{ env.CONTAINER_APP_ENVIRONMENT }}
        image: ${{ env.REGISTRY_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        registry-login-server: ${{ env.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ env.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        environment-variables: |
          REACT_APP_ENVIRONMENT=production
          REACT_APP_API_BASE_URL=${{ secrets.API_BASE_URL }}
          REACT_APP_GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          REACT_APP_MICROSOFT_CLIENT_ID=${{ secrets.MICROSOFT_CLIENT_ID }}
          REACT_APP_APPLE_CLIENT_ID=${{ secrets.APPLE_CLIENT_ID }}
          REACT_APP_FACEBOOK_CLIENT_ID=${{ secrets.FACEBOOK_CLIENT_ID }}
        cpu: 0.25
        memory: 0.5Gi
        min-replicas: 0
        max-replicas: 10
        target-port: 80