name: Build and Push to Azure Container Registry

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY_LOGIN_SERVER: wihymlregistry-b6fdh5cmhzgwbbgy.azurecr.io
  IMAGE_NAME: wihy-ui

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm ci
    
    - name: Install client dependencies
      run: |
        cd client
        npm ci
    
    - name: Run client tests
      run: |
        cd client
        npm test -- --coverage --watchAll=false
    
    - name: Build client
      run: |
        cd client
        npm run build

  build-and-push-azure:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check Azure credentials
      run: |
        if [ -z "${{ secrets.AZURE_CLIENT_ID }}" ] || [ -z "${{ secrets.AZURE_TENANT_ID }}" ]; then
          echo "⚠️ Azure credentials not configured"
          echo "Please see docs/AZURE_GITHUB_ACTIONS_SETUP.md for setup instructions"
          echo "Skipping Azure deployment..."
          exit 0
        fi
        echo "✅ Azure credentials configured"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Debug Azure Container Registries
      run: |
        echo "🔍 Listing Azure Container Registries..."
        az acr list --query "[].{Name:name, LoginServer:loginServer, ResourceGroup:resourceGroup}" -o table
        
        echo ""
        echo "🔍 Checking specific resource group (vHealth)..."
        az acr list --resource-group vHealth --query "[].{Name:name, LoginServer:loginServer}" -o table || echo "No registries in vHealth RG"
        
        echo ""
        echo "🔍 Looking for WIHY registries..."
        az acr list --query "[?contains(name, 'wihy')].{Name:name, LoginServer:loginServer}" -o table

    - name: Log in to Azure Container Registry
      run: |
        echo "🔍 Attempting to find and login to registry..."
        
        # Get the actual registry name that contains 'wihy'
        REGISTRY_NAME=$(az acr list --query "[?contains(name, 'wihy')].name" -o tsv | head -1)
        
        if [ -z "$REGISTRY_NAME" ]; then
          echo "❌ No WIHY registry found!"
          az acr list --query "[].{Name:name, LoginServer:loginServer}" -o table
          exit 1
        fi
        
        echo "✅ Found registry: $REGISTRY_NAME"
        az acr login --name $REGISTRY_NAME

    - name: Build and push Docker image
      run: |
        echo "🔍 Getting actual registry name..."
        REGISTRY_NAME=$(az acr list --query "[?contains(name, 'wihy')].name" -o tsv | head -1)
        
        if [ -z "$REGISTRY_NAME" ]; then
          echo "❌ No WIHY registry found for build!"
          exit 1
        fi
        
        echo "✅ Building with registry: $REGISTRY_NAME"
        az acr build \
          --registry $REGISTRY_NAME \
          --image ${{ env.IMAGE_NAME }}:${{ github.sha }} \
          --image ${{ env.IMAGE_NAME }}:latest \
          .

    - name: Image Info
      run: |
        echo "🐳 Container images published to Azure Container Registry:"
        echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
        echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
        echo ""
        echo "✅ Ready for Azure Container Apps deployment!"