name: Build and Push to Azure Container Registry

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io
  IMAGE_NAME: wihy-ui

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install root dependencies
      run: npm ci
    
    - name: Install client dependencies
      run: |
        cd client
        npm ci
    
    - name: Run client tests
      run: |
        cd client
        npm test -- --coverage --watchAll=false
    
    - name: Build client
      run: |
        cd client
        npm run build

  build-and-push-azure:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Check Azure credentials
      run: |
        if [ -z "${{ secrets.AZURE_CREDENTIALS }}" ] || [ -z "${{ secrets.REGISTRY_PASSWORD }}" ]; then
          echo "⚠️ Azure credentials not configured"
          echo "Please add the required GitHub secrets:"
          echo "- AZURE_CREDENTIALS (JSON format)"
          echo "- REGISTRY_PASSWORD"
          echo "- AZURE_CONTAINER_REGISTRY"
          echo "- REGISTRY_USERNAME"
          echo "Skipping Docker build..."
          exit 0
        fi
        echo "✅ Azure credentials configured"

    - name: Debug Registry Configuration
      run: |
        echo "🔍 Registry Configuration Debug:"
        echo "REGISTRY: ${{ env.REGISTRY }}"
        echo "AZURE_CONTAINER_REGISTRY secret: ${{ secrets.AZURE_CONTAINER_REGISTRY }}"
        echo "REGISTRY_USERNAME secret: ${{ secrets.REGISTRY_USERNAME }}"
        echo "Expected full URL: ${{ secrets.AZURE_CONTAINER_REGISTRY }}.azurecr.io"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Login to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        platforms: linux/amd64
        # Remove cache options that cause issues with GitHub Actions
        # cache-from: type=gha
        # cache-to: type=gha,mode=max

    - name: Image Info
      run: |
        echo "🐳 Container images published to Azure Container Registry:"
        echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest"
        echo "${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
        echo ""
        echo "✅ Ready for Azure Container Apps deployment!"