name: Test Azure Authentication

on:
  workflow_dispatch:

jobs:
  test-auth:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Check if secrets are available
      run: |
        echo "🔍 Checking GitHub secrets availability..."
        
        if [ -z "${{ secrets.AZURE_CLIENT_ID }}" ]; then
          echo "❌ AZURE_CLIENT_ID secret is missing"
        else
          echo "✅ AZURE_CLIENT_ID secret is set"
        fi
        
        if [ -z "${{ secrets.AZURE_TENANT_ID }}" ]; then
          echo "❌ AZURE_TENANT_ID secret is missing"
        else
          echo "✅ AZURE_TENANT_ID secret is set"
        fi
        
        if [ -z "${{ secrets.AZURE_SUBSCRIPTION_ID }}" ]; then
          echo "❌ AZURE_SUBSCRIPTION_ID secret is missing"
        else
          echo "✅ AZURE_SUBSCRIPTION_ID secret is set"
        fi
        
        if [ -z "${{ secrets.REGISTRY_PASSWORD }}" ]; then
          echo "❌ REGISTRY_PASSWORD secret is missing"
        else
          echo "✅ REGISTRY_PASSWORD secret is set"
        fi
    
    - name: Test Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    
    - name: Verify Azure Access
      run: |
        echo "🔍 Testing Azure CLI access..."
        az account show --query "{subscriptionId: id, tenantId: tenantId}" -o table
        
        echo "🔍 Testing access to vhealth resource group..."
        az group show --name vhealth --query name -o tsv
        
        echo "🔍 Testing Container App access..."
        az containerapp show --name wihy-ui --resource-group vhealth --query name -o tsv
        
        echo "✅ Azure authentication test completed successfully!"